DEBUG 2021-04-15 09:41:47.504 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-15 09:41:47.504 UTC: 	 Running on: Linux cmslpc132.fnal.gov 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 10 08:19:23 CST 2020 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2021-04-15 09:41:47.504 UTC: 	 Executing command: 'status'
DEBUG 2021-04-15 09:41:47.509 UTC: 	 Found CRAB cache file /uscms/home/cannaert/.crab3
ERROR 2021-04-15 09:41:47.516 UTC: 	 Cannot find .requestcache file in CRAB project directory /uscms_data/d3/cannaert/UL2018_genproduction/Suu8TeV_chi3TeV/CMSSW_10_6_17_patch1/src/crab_projects
ERROR 2021-04-15 09:41:47.516 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 643, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 505, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /uscms_data/d3/cannaert/UL2018_genproduction/Suu8TeV_chi3TeV/CMSSW_10_6_17_patch1/src/crab_projects
INFO 2021-04-15 09:41:47.527 UTC: 	 Log file is /uscms_data/d3/cannaert/UL2018_genproduction/Suu8TeV_chi3TeV/CMSSW_10_6_17_patch1/src/crab.log
